<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Job;
use App\Models\Company;
use App\Models\Location;
use App\Models\JobCategory;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $employmentTypeMap = [
            '正社員'     => 1,
            '契約社員'   => 2,
            '派遣社員'   => 3,
            'アルバイト' => 4,
            'パート'     => 5,
        ];

        // 小カテゴリーから10件取得
        $categories = JobCategory::whereNotNull('parent_id')->inRandomOrder()->limit(10)->get();
        $companies = Company::all();
        $locations = Location::all();

        $jobs = [
            [
                'title' => 'Webフロントエンドエンジニア',
                'location' => '東京都渋谷区',
                'location_id' => optional($locations->where('name', '東京都')->first())->id,
                'salary_min' => 500,
                'salary_max' => 700,
                'employment_type' => '正社員',
                'description' => 'Vue.js/ReactでのSPA開発。UI/UX改善にも携われます。',
                'requirements' => 'JavaScriptの実務経験2年以上。CSS設計経験者。',
                'welcome_skills' => 'FigmaやTypeScriptの経験があれば歓迎します。',
                'required_qualifications' => '学歴不問／情報処理技術者資格歓迎',
                'tools' => 'Vue.js, React, Figma, Git',
                'selection_flow' => "書類選考 → 一次面接（WEB）→ 最終面接 → 内定",
                'required_documents' => "履歴書・職務経歴書（PDF可）",
                'interview_place' => "本社（渋谷区）またはオンライン面接可",
                'benefits' => 'リモート可・住宅手当あり・交通費支給。',
                'work_time' => '10:00～19:00（フレックス有）',
                'holiday' => '完全週休2日制（土日）・祝日・夏季・年末年始',
                'number_of_positions' => 2,
            ],
            [
                'title' => 'バックエンドエンジニア（PHP/Laravel）',
                'location' => '大阪府大阪市',
                'location_id' => optional($locations->where('name', '大阪府')->first())->id,
                'salary_min' => 450,
                'salary_max' => 600,
                'employment_type' => '正社員',
                'description' => 'LaravelベースのAPI開発。新規サービスの設計～運用。',
                'requirements' => 'PHP実務経験3年以上。Git利用経験。',
                'welcome_skills' => 'AWSやDockerの利用経験者歓迎。',
                'required_qualifications' => '専門卒以上／LPIC保有者優遇',
                'tools' => 'Laravel, MySQL, AWS, Docker',
                'selection_flow' => "書類選考 → コーディングテスト → 面接 → 内定",
                'required_documents' => "履歴書、職務経歴書、ポートフォリオ（任意）",
                'interview_place' => "大阪本社またはWEB面接",
                'benefits' => '私服勤務OK・資格取得支援。',
                'work_time' => '9:30～18:30',
                'holiday' => '週休2日制・祝日・有給休暇',
                'number_of_positions' => 1,
            ],
            [
                'title' => 'Webデザイナー',
                'location' => '東京都港区',
                'location_id' => optional($locations->where('name', '東京都')->first())->id,
                'salary_min' => 350,
                'salary_max' => 500,
                'employment_type' => '契約社員',
                'description' => 'コーポレートサイトやLPのデザイン。Figma/Photoshop経験歓迎。',
                'requirements' => 'Webデザインの実務経験1年以上。',
                'welcome_skills' => 'バナー制作・UI/UX設計経験。',
                'required_qualifications' => '高卒以上／デザイン系資格保持者優遇',
                'tools' => 'Figma, Photoshop, Illustrator',
                'selection_flow' => "書類選考 → ポートフォリオ審査 → 面接 → 内定",
                'required_documents' => "履歴書・職務経歴書・ポートフォリオ",
                'interview_place' => "東京オフィスまたはリモート面接",
                'benefits' => 'リモート可・PC貸与。',
                'work_time' => '9:00～18:00',
                'holiday' => '土日祝・年末年始',
                'number_of_positions' => 1,
            ],
            [
                'title' => '法人営業',
                'location' => '愛知県名古屋市',
                'location_id' => optional($locations->where('name', '愛知県')->first())->id,
                'salary_min' => 400,
                'salary_max' => 480,
                'employment_type' => '正社員',
                'description' => '自社ITサービスの新規開拓営業。リモート相談OK。',
                'requirements' => '法人営業経験者歓迎。IT業界未経験OK。',
                'welcome_skills' => 'SaaS営業経験・営業マネジメント経験者歓迎。',
                'required_qualifications' => '要普通免許／大卒以上',
                'tools' => 'Excel, PowerPoint, Salesforce',
                'selection_flow' => "書類選考 → 一次面接 → 二次面接 → 内定",
                'required_documents' => "履歴書・職務経歴書",
                'interview_place' => "名古屋本社",
                'benefits' => 'インセンティブ有・社用スマホ貸与。',
                'work_time' => '9:00～18:00',
                'holiday' => '土日祝',
                'number_of_positions' => 3,
            ],
            [
                'title' => 'インフラエンジニア（AWS）',
                'location' => '福岡県福岡市',
                'location_id' => optional($locations->where('name', '福岡県')->first())->id,
                'salary_min' => 530,
                'salary_max' => 800,
                'employment_type' => '正社員',
                'description' => 'AWS環境構築、運用保守。IaCの推進もお願いします。',
                'requirements' => 'インフラ運用保守経験。AWS知識。',
                'welcome_skills' => 'Terraform経験者歓迎。',
                'required_qualifications' => 'AWS認定資格保持者歓迎',
                'tools' => 'AWS, Terraform, Linux, Shell',
                'selection_flow' => "書類選考 → 技術面接 → 最終面接 → 内定",
                'required_documents' => "履歴書・職務経歴書",
                'interview_place' => "福岡支社またはWEB面接",
                'benefits' => 'リモート勤務可・資格手当有。',
                'work_time' => '10:00～19:00',
                'holiday' => 'シフト制（週休2日）',
                'number_of_positions' => 2,
            ],
            [
                'title' => 'デジタルマーケター',
                'location' => '東京都中央区',
                'location_id' => optional($locations->where('name', '東京都')->first())->id,
                'salary_min' => 400,
                'salary_max' => 600,
                'employment_type' => '契約社員',
                'description' => 'SEO/SEM・SNS広告運用。EC分野の拡大を担います。',
                'requirements' => 'デジタル広告運用の経験者。',
                'welcome_skills' => 'EC・D2Cの知識。',
                'required_qualifications' => '学歴不問／広告関連資格あれば尚可',
                'tools' => 'Google Analytics, Ads, SNS各種',
                'selection_flow' => "書類選考 → 一次面接 → WEB課題 → 内定",
                'required_documents' => "履歴書・職務経歴書",
                'interview_place' => "東京オフィスまたはリモート面接",
                'benefits' => '正社員登用有・リモート可。',
                'work_time' => '9:30～18:30',
                'holiday' => '土日祝',
                'number_of_positions' => 1,
            ],
            [
                'title' => 'プロジェクトマネージャー',
                'location' => '北海道札幌市',
                'location_id' => optional($locations->where('name', '北海道')->first())->id,
                'salary_min' => 650,
                'salary_max' => 850,
                'employment_type' => '正社員',
                'description' => '開発チームの進行管理・クライアント折衝・予算管理。',
                'requirements' => 'PM経験必須。マネジメントスキル。',
                'welcome_skills' => 'SIer出身者歓迎。',
                'required_qualifications' => '大卒以上／PMP資格保有者歓迎',
                'tools' => 'Redmine, JIRA, Office365',
                'selection_flow' => "書類選考 → マネジメント課題 → 面接 → 内定",
                'required_documents' => "履歴書・職務経歴書・資格証明書",
                'interview_place' => "札幌オフィスまたはオンライン",
                'benefits' => '家賃補助・フレックス勤務有。',
                'work_time' => '9:00～18:00（フレックス有）',
                'holiday' => '完全週休2日制（土日祝）',
                'number_of_positions' => 1,
            ],
            [
                'title' => 'データサイエンティスト',
                'location' => '京都府京都市',
                'location_id' => optional($locations->where('name', '京都府')->first())->id,
                'salary_min' => 600,
                'salary_max' => 850,
                'employment_type' => '正社員',
                'description' => 'ビッグデータ解析・AIモデル設計、Python/R活用。',
                'requirements' => 'Python/R経験必須。',
                'welcome_skills' => '深層学習・論文読解経験。',
                'required_qualifications' => '理系大学院卒優遇／英語論文読解力',
                'tools' => 'Python, R, Jupyter, SQL',
                'selection_flow' => "書類選考 → 技術面接 → 最終面接 → 内定",
                'required_documents' => "履歴書・職務経歴書・論文要約（任意）",
                'interview_place' => "京都本社またはWEB面接",
                'benefits' => '書籍購入補助・勉強会支援。',
                'work_time' => '10:00～19:00',
                'holiday' => '完全週休2日制（土日祝）',
                'number_of_positions' => 2,
            ],
            [
                'title' => '一般事務',
                'location' => '兵庫県神戸市',
                'location_id' => optional($locations->where('name', '兵庫県')->first())->id,
                'salary_min' => 300,
                'salary_max' => 380,
                'employment_type' => '契約社員',
                'description' => 'データ入力・電話応対・文書管理等の一般事務業務。',
                'requirements' => 'PC操作・電話対応経験。',
                'welcome_skills' => '簿記資格あれば尚可。',
                'required_qualifications' => '高卒以上／簿記3級以上あれば尚可',
                'tools' => 'Excel, Word, PowerPoint',
                'selection_flow' => "書類選考 → 一次面接 → 内定",
                'required_documents' => "履歴書・職務経歴書",
                'interview_place' => "神戸本社またはリモート面接",
                'benefits' => '時短勤務相談可・交通費全額支給。',
                'work_time' => '9:00～17:00',
                'holiday' => '土日祝',
                'number_of_positions' => 2,
            ],
            [
                'title' => '小売業スタッフ',
                'location' => '神奈川県横浜市',
                'location_id' => optional($locations->where('name', '神奈川県')->first())->id,
                'salary_min' => 300,
                'salary_max' => 350,
                'employment_type' => '正社員',
                'description' => '販売・接客。未経験歓迎。シフト勤務可。',
                'requirements' => '接客経験不問。元気な方歓迎。',
                'welcome_skills' => '販売経験ある方優遇。',
                'required_qualifications' => '高卒以上',
                'tools' => 'POSレジ, Excel',
                'selection_flow' => "書類選考 → 面接 → 内定",
                'required_documents' => "履歴書",
                'interview_place' => "横浜店舗または本社",
                'benefits' => '社割・制服貸与。',
                'work_time' => 'シフト制（9:00～21:00の間）',
                'holiday' => 'シフトによる週休2日',
                'number_of_positions' => 4,
            ],
        ];

        foreach ($jobs as $i => $job) {
            $typeValue = $employmentTypeMap[$job['employment_type']] ?? 1;
            Job::create([
                'company_id'              => $companies->random()->id,
                'job_category_id'         => $categories[$i % $categories->count()]->id,
                'location_id'             => $job['location_id'],
                'title'                   => $job['title'],
                'location'                => $job['location'],
                'salary_min'              => $job['salary_min'],
                'salary_max'              => $job['salary_max'],
                'employment_type'         => $typeValue,
                'description'             => $job['description'],
                'requirements'            => $job['requirements'],
                'welcome_skills'          => $job['welcome_skills'],
                'required_qualifications' => $job['required_qualifications'],
                'tools'                   => $job['tools'],
                'selection_flow'          => $job['selection_flow'],
                'required_documents'      => $job['required_documents'],
                'interview_place'         => $job['interview_place'],
                'benefits'                => $job['benefits'],
                'work_time'               => $job['work_time'],
                'holiday'                 => $job['holiday'],
                'number_of_positions'     => $job['number_of_positions'],
                'is_active'               => true,
                'is_featured'             => $i < 5,
                'application_deadline'    => now()->addDays(30),
            ]);
        }
    }
}
